<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tblCountry".
 *
 * @property integer $countrySID
 * @property string $countryName
 * @property string $aliasModel
 */
abstract class Country extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tblCountry';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['countryName'], 'required'],
            [['countryName'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'countrySID' => 'Country Sid',
            'countryName' => 'Country Name',
        ];
    }




}
