<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "field_alias".
 *
 * @property integer $id
 * @property string $type
 * @property string $field_name
 * @property string $label_name
 * @property string $aliasModel
 */
abstract class FieldAlias extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'field_alias';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'field_name', 'label_name'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'field_name' => 'Field Name',
            'label_name' => 'Label Name',
        ];
    }




}
