<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "report_template".
 *
 * @property integer $id
 * @property string $report_name
 * @property string $report_description
 * @property string $field_order
 * @property string $filter
 * @property integer $limit_per_page
 * @property string $sorting_order
 * @property string $client_filter
 * @property string $created_by
 * @property string $updated_by
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class ReportTemplate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'report_template';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['report_name', 'report_description', 'field_order', 'filter', 'sorting_order', 'client_filter'], 'string'],
            [['report_name', 'report_description'], 'required'],
            [['limit_per_page'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'report_name' => 'Report Name',
            'report_description' => 'Report Description',
            'field_order' => 'Field Order',
            'filter' => 'Filter',
            'limit_per_page' => 'Limit Per Page',
            'sorting_order' => 'Sorting Order',
            'client_filter' => 'Client Filter',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }




}
