<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "tblShipment".
 *
 * @property integer $ShipmentSID
 * @property integer $MasterSID
 * @property string $ShipmentCode
 * @property string $ShipmentSenderAddress1
 * @property string $ShipmentSenderAddress2
 * @property string $ShipmentSenderAddress3
 * @property integer $ShipmentSenderCountrySID
 * @property string $ShipmentReceiverAddress1
 * @property string $ShipmentReceiverAddress2
 * @property string $ShipmentReceiverAddress3
 * @property integer $ShipmentReceiverCountrySID
 * @property string $ShipmentWeight
 * @property string $ShipmentDeadWeight
 * @property integer $ShipmentNumOfItems
 * @property string $ShipmentReference
 * @property integer $ShipmentCustomerSID
 * @property string $ShipmentSenderReference
 * @property string $ShipmentCreatedDate
 * @property integer $ShipmentCreatedBy
 * @property string $aliasModel
 */
abstract class Shipment extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tblShipment';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'ShipmentCreatedDate',
                'updatedAtAttribute' => 'ShipmentCreatedBy',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['MasterSID', 'ShipmentCode', 'ShipmentSenderAddress1', 'ShipmentSenderAddress2', 'ShipmentSenderAddress3', 'ShipmentSenderCountrySID', 'ShipmentReceiverAddress1', 'ShipmentReceiverAddress2', 'ShipmentReceiverAddress3', 'ShipmentReceiverCountrySID', 'ShipmentWeight', 'ShipmentDeadWeight', 'ShipmentNumOfItems', 'ShipmentReference', 'ShipmentCustomerSID', 'ShipmentSenderReference'], 'required'],
            [['MasterSID', 'ShipmentSenderCountrySID', 'ShipmentReceiverCountrySID', 'ShipmentNumOfItems', 'ShipmentCustomerSID'], 'integer'],
            [['ShipmentCode', 'ShipmentSenderAddress1', 'ShipmentSenderAddress2', 'ShipmentSenderAddress3', 'ShipmentReceiverAddress1', 'ShipmentReceiverAddress2', 'ShipmentReceiverAddress3', 'ShipmentReference', 'ShipmentSenderReference'], 'string'],
            [['ShipmentWeight', 'ShipmentDeadWeight'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ShipmentSID' => 'Shipment Sid',
            'MasterSID' => 'Master Sid',
            'ShipmentCode' => 'Shipment Code',
            'ShipmentSenderAddress1' => 'Shipment Sender Address1',
            'ShipmentSenderAddress2' => 'Shipment Sender Address2',
            'ShipmentSenderAddress3' => 'Shipment Sender Address3',
            'ShipmentSenderCountrySID' => 'Shipment Sender Country Sid',
            'ShipmentReceiverAddress1' => 'Shipment Receiver Address1',
            'ShipmentReceiverAddress2' => 'Shipment Receiver Address2',
            'ShipmentReceiverAddress3' => 'Shipment Receiver Address3',
            'ShipmentReceiverCountrySID' => 'Shipment Receiver Country Sid',
            'ShipmentWeight' => 'Shipment Weight',
            'ShipmentDeadWeight' => 'Shipment Dead Weight',
            'ShipmentNumOfItems' => 'Shipment Num Of Items',
            'ShipmentReference' => 'Shipment Reference',
            'ShipmentCustomerSID' => 'Shipment Customer Sid',
            'ShipmentSenderReference' => 'Shipment Sender Reference',
            'ShipmentCreatedDate' => 'Shipment Created Date',
            'ShipmentCreatedBy' => 'Shipment Created By',
        ];
    }




}
